name: maven-local

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew publishToMavenLocal
      - uses: actions/upload-artifact@v2
        with:
          name: publishToMavenLocal
          path: "~/.m2/**"
